apiVersion: v1
kind: Namespace
metadata:
  name: plex-server

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-data-01-sc
  namespace: plex-server
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-data-02-sc
  namespace: plex-server
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-config-sc
  namespace: plex-server
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-trans-sc
  namespace: plex-server
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: plex-data-01-pv
  namespace: plex-server
spec:
  storageClassName: plex-data-01-sc
  capacity:
    storage: 433Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: "/storage/hd2/plex"
    server: "10.1.1.3"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: plex-data-02-pv
  namespace: plex-server
spec:
  storageClassName: plex-data-02-sc
  capacity:
    storage: 213Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: "/storage/hd1/plex"
    server: "10.1.1.2"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: plex-config-pv
  namespace: plex-server
spec:
  storageClassName: plex-config-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: "/storage/hd0/plex/config"
    server: "10.1.1.200"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: plex-trans-pv
  namespace: plex-server
spec:
  storageClassName: plex-trans-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: "/storage/hd0/plex/transcode"
    server: "10.1.1.200"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-data-01-pvc
  namespace: plex-server
spec:
  storageClassName: plex-data-01-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 433Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-data-02-pvc
  namespace: plex-server
spec:
  storageClassName: plex-data-02-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 213Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config-pvc
  namespace: plex-server
spec:
  storageClassName: plex-config-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-trans-pvc
  namespace: plex-server
spec:
  storageClassName: plex-trans-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex-server
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
   - name: tcp-32400
     protocol: TCP
     port: 32400
     targetPort: 32400
  selector:
    app: plex-server
status: {}
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: plex-server
spec:
  replicas: 2
  selector:
      matchLabels:
        app: plex-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex-server
    spec:
      containers:
      - env:
        - name: PLEX_GID
          value: "1001"
        - name: PLEX_UID
          value: "1001"
        - name: TZ
          value: "America/Sao_Paulo"
        - name: PLEX_CLAIM
          value: "claim-FKRucvRSh432mkzyyNkv"
        image: plexinc/pms-docker
        name: plex-server
        ports:
        - containerPort: 32400
        resources:
          limits:
            cpu: "3"
            memory: "2Gi"
          requests:
            cpu: "300m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /data-01/
          name: plex-data-01
        - mountPath: /data-02/
          name: plex-data-02
        - mountPath: /config
          name: plex-config
        - mountPath: /transcode
          name: plex-trans
      restartPolicy: Always
      volumes:
      - name: plex-data-01
        persistentVolumeClaim:
          claimName: plex-data-01-pvc
      - name: plex-data-02
        persistentVolumeClaim:
          claimName: plex-data-02-pvc
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: plex-trans
        persistentVolumeClaim:
          claimName: plex-trans-pvc
status: {}

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: plex-ingressclass
  namespace: plex-server
spec:
  controller: nginx.org/ingress-controller 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex-server
spec:
  defaultBackend:
    service:
      name: plex-service
      port:
        number: 32400
  ingressClassName: plex-ingressclass
  tls:
  - hosts:
    - plex.nb41.tech
    secretName: plex-secret
  rules:
  - host: plex.nb41.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex-service
            port:
              number: 32400